### ISSUE TITLE
Syntax is very dim

### ISSUE THREAD

**Issue by tyler-reitz** [coopermaruyama/atom-vivid-syntax#4]
atom-version: 1.18.0-beta2 x64
macOS: 10.10.3

I'm getting a very dim display even after having tried adjusting the calibrated settings in the readme. Uninstalled and re-installed as well, but  no luck.

![screen shot 2017-05-27 at 4 42 52 pm](https://cloud.githubusercontent.com/assets/8248045/26524948/d8f3fc82-42fb-11e7-9598-0d42854ab657.png)

**Comment by czxtm** [comment]
Hey, I noticed this happen after a recent atom update. I'm looking into it now. A workaround in the meantime is to split your pane (so you have 2 panes), then close one of the panes. Let me know if it fixes the issue.

**Comment by czxtm** [comment]
I've updated the theme with a fix. Please update and let me know if the issue persists.

Relevant atom issue is tracked here: https://github.com/atom/atom/issues/14283

**Comment by tyler-reitz** [comment]
That worked. Thank you!
